-=ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ=-
                            ÜÜ TM
      ÜÜÜÜÜÜ   ÜÜÜÜÜÜÜ   ÜÜÜÛÛ
     ÛÛ   ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ  ÛÛ
     ÛÛÛÛ ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ  ÛÛ
     ßß   ßß  ßß ßß ßß  ßßßßß
              pREsen+S
    =-=----------------------=-=

      A New Game Õrom SmOkErS
         'Fields Of L0g!c'
              (c) 1999
     Based By Volker Stepprath

    =-=----------------------=-=
-=ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ=-
-=ÄÄÄÄÄÄÄÄ´CreDit5 Stuff!ÃÄÄÄÄÄÄÄÄ=-

inTro iDea.......WrecKer/Sm0kers/aMd
inTro (0diNg.....Baz0FFt/Sm0kers/aMd
inTro grAphiX....WrecKer/Sm0kers/aMd
inTro muZic......Baz0FFt/Sm0kers/aMd
inTro suPport........Sat/Sm0kers/aMd
game iDea........Baz0FFt/Sm0kers/aMd
game (0diNg......Baz0FFt/Sm0kers/aMd
game grAphiX.....WrecKer/Sm0kers/aMd
game muZics......Baz0FFt/Sm0kers/aMd
game teZterZ.....Urri n' Necromancer
i-Net acces..........Paul Pavlov/aMd
eXport...........................aMd

-=ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ=-
úúúúaMd Gr@ets /in Random Order/úúúú

           ÕaTAÀi+y  Rage
         @-Mage  Ascendancy
          RealSoft Fantazm
          Destruction Team 
   Zer0  Phantasy  Serious Spe((y
 0mega HG  Digital ReaÀity  ExtÚeme
  GoldenDi5k  Virtual Vi5ion GroÓp
          Dj Z¢ãk  Dj Catz
           Flash  Antares
         Rea(tion  Progres5
      X-Project Alex Nikiforov
             - - - - -
 AndAllOtherWhoKeepSpeccySceneAlive
             - - - - -
ú (oÖTAct US, wRiTE U5, cHat to US ú

plz, our @-mailes:
               paul.pavlov@usa.net
               beard.yury@usa.net
               tankard.aMd@usa.net

(017)270-95-12......Baz0FFt /­¤àî/
(017)271-23-24......WrecKer \ ¢¥«\
(sEx)PR!-VA-TE...........Sat \Š®áâï\
(017)249-63-14.........BeaRd / à  /

      Visit Our Côôl Home Page:

 http://www.fortunecity.com/
      underworld/worms/43/main.html
-=ÄÄÄÄÄÄÄÄÄÄ´Last Page!ÃÄÄÄÄÄÄÄÄÄÄ=-


    ÚÄÄÄúúúúúúúúúúúúúúúúúúúúÄÄÄ¿
    ÚÄúúúúúúúúúúúúúúúúúúúúúúúúÄ¿
    ú                          ú
      Date Of Release: 16-Feb-99
        Place: Minsk/Belarus
    úúú                      úúú
             cYa, dudz!
    ú                          ú
    ÀÄúúúúúúúúúúúúúúúúúúúúúúúúÄÙ
    ÀÄÄúúúúúúúúúúúúúúúúúúúúúúÄÄÙ


-=ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ=-
-=ÄÄÄÄÄÄÄÄÄÄ´PostscRIPtÃÄÄÄÄÄÄÄÄÄÄ=-

 Ã\nal (C)ut              /^\
                         |aMd|
          /^\_/^\    ___  \ /
         /===   |   /   \ | |
       \ @  @ /  \/       \/
      --<^_ <--_     /\   |
       / `---'\ `\  | |  /
                  | | | |
                 <__><__>
...Ego scales my skin
       I grab a sharp stick
               And I cut my gills...

-=ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ=-
